changelog:
  categories:
    - title: Features
      labels:
        - feat
        - feature
        - build
        - ci
    - title: Bug Fixes
      labels:
        - fix
        - bug
        - hotfix
