changelog:
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - fix
          - bug
    - title: BugFixes
      labels:
        - fix
        - bug
