changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - fix
          - bug
    - title: BugFixes
      labels:
        - fix
        - bug
