name: GLPI Android Inventory Library CI

env:
  # The name of the main module repository
  module_java: example_java
  module_kotlin: example_kotlin

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build project
    - name: Build with Gradle
      run: ./gradlew build

    # Create APK Debug
    - name: Build apk debug project (APK)
      run: ./gradlew assembleDebug

    # Create APK Release
    - name: Build apk release project (APK)
      run: ./gradlew assemble

    # Create ZIP artifact for module_java (without build folder)
    - name: ZIP artifact for module_java
      run: zip java_example_code.zip ${{ env.module_java }} -x ${{ env.module_java }}/build/

    # Create ZIP archive for module_kotlin (without build folder)
    - name: ZIP archive for module_kotlin
      run: zip kotlin_example_code.zip ${{ env.module_kotlin }} -x ${{ env.module_kotlin }}/build/

    # Upload APK Artifact for for module_java
    - name: Upload APK Debug for Java
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.module_java }} - APK debug
        path: ${{ env.module_java }}/build/outputs/apk/debug/

    # Upload APK Artifact for module_kotlin
    - name: Upload APK Debug for Kotlin
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.module_kotlin }} - APK debug
        path: ${{ env.module_kotlin }}/build/outputs/apk/debug/

    # Upload ZIP file for module_java
    - name: Upload ZIP Library Debug - Java
      uses: actions/upload-artifact@v3
      with:
        path: java_example_code.zip

    # Upload ZIP file for module_kotlin
    - name: Upload ZIP Library Debug - Kotlin
      uses: actions/upload-artifact@v3
      with:
        path: kotlin_example_code.zip
